name: Go Build & Test
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '*'
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        # os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Build & Test
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: '1.18'
    - name: Build & Test
      run: |
        go build -v
        go test ./...
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v3
      with:
        args: release --snapshot --skip-publish --rm-dist
    